#!/bin/bash
set -eo pipefail
# vim: set ts=8 shiftwidth=4 softtabstop=4 expandtab smarttab colorcolumn=80:
#
# Copyright (c) 2021 Red Hat, Inc.
# Author: Sergio Correia <scorreia@redhat.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

PIN_NAME=pkcs11

on_exit() {
    [ -d "${CLEVIS_PKCS11}" ] || exit 0
    rm -rf "${CLEVIS_PKCS11}"
}
unset CLEVIS_PKCS11

# We first check whether the configuration is a valid JSON.
if ! cfg="$(jose fmt --json="$1" --object --output=- 2>/dev/null)" ; then
    echo 'Configuration is malformed' >&2
    exit 1
fi

if ! CLEVIS_PKCS11="$(mktemp -d)" || [ -z "${CLEVIS_PKCS11}" ]; then
    echo "Creating a temporary dir for PKCS11 files failed" >&2
    exit 1
fi
trap 'on_exit' EXIT

# Let's generate a key.
if ! jwk="$(jose jwk gen --input='{"alg":"A256GCM"}')" \
            || [ -z "${jwk}" ]; then
    echo "Unable to generate JWK" >&2
    exit 1
fi

# Now let's encrypt it with the device public key.
PKEY="${CLEVIS_PKCS11}/pubkey"
if ! pkcs15-tool --read-public-key 03 > "${PKEY}"; then
    echo "Unable to obtain a public key from PKCS#11 device" >&2
    exit 1
fi

if ! jwk_enc="$(printf '%s' "${jwk}" | openssl rsautl -encrypt -pubin \
                                       -inkey "${PKEY}" 2>/dev/null \
                                     | jose b64 enc -I-)"; then
    echo "Unable to encrypt JWK with PKCS#11 public key" >&2
    exit 1
fi

# And the JWE.
template=$(printf '{"protected":{"clevis":{"pin":"%s","%s":{}}}}' \
                  "${PIN_NAME}" "${PIN_NAME}")

# Save key.
jwe="$(jose fmt --json="${template}" --get protected --get clevis \
       --get "${PIN_NAME}" --quote "${jwk_enc}" --set key -UUUU --output=-)"

# Now we encrypt the data using our key.
( printf '%s' "${jwe}${jwk}" ; cat ) | exec jose jwe enc \
                                            --input=- --key=- \
                                            --detached=- --compact
