#!/bin/bash
# vim: set ts=8 shiftwidth=4 softtabstop=4 expandtab smarttab colorcolumn=80:
#
# Copyright (c) 2024 Red Hat, Inc.
# Author: Sergio Arroutbi <sarroutb@redhat.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
if [ "$1" == "--summary" ]; then
    exit 1
fi

URI_EXPECTED_FORMAT="pkcs11:"

clevis_valid_pkcs11_uri() {
    echo "$1" | grep -E "^${URI_EXPECTED_FORMAT}" >/dev/null 2>&1 || return 1
}

clevis_get_module_path_from_uri() {
    echo "$1" | grep -E "module-path=" >/dev/null 2>&1 || return 1
    echo "$1" | awk -F 'module-path=' '{print $2}' | awk -F ";" '{print $1}' \
        | awk -F "?" '{print $1}'
}

clevis_get_pin_value_from_uri() {
    echo "$1" | grep -E "pin-value=" >/dev/null 2>&1 || return 1
    echo "$1" | awk -F 'pin-value=' '{print $2}' | awk -F ";" '{print $1}'
}

clevis_get_slot_from_uri() {
    echo "$1" | grep -E "slot=" >/dev/null 2>&1 || return 1
    echo "$1" | awk -F 'slot=' '{print $2}' | awk -F ";" '{print $1}' \
        | awk -F "?" '{print $1}'
}

clevis_get_max_pkcs11_slot() {
    pkcs11-tool -L | grep -i "^slot" | awk '{print $2}' | tail -1
}

clevis_pkcs11_filter_uri() {
    echo "$1" | sed -E 's@module-path=[a-z,A-Z,0-9,/,.]{1,};{0,1}@@' | sed -E 's@;$@@g'
}

clevis_get_pkcs11_pubkey_slot_from_uri() {
    if ! module_path=$(clevis_get_module_path_from_uri "${1}"); then
        module_opt=""
    else
	module_opt=" --module ${module_path}"
    fi
    uri=$(clevis_pkcs11_filter_uri "${1}")
    for ((s=0; s<=$(clevis_get_max_pkcs11_slot); s++))
    do
        if pkcs11-tool ${module_opt} --slot-index ${s} --type pubkey -O 2>/dev/null | grep -i 'uri:' | awk -F 'uri:' '{print $2}' | tr -d ' ' | grep "${uri}" 2>/dev/null 1>/dev/null; then
            echo "${s}"
	fi
    done
}
