#!/bin/bash
###       If pkcs11 configuration exists, try to start pcscd
if command -v pcscd; then
  echo "clevis-pkcs11: starting pcscd if not available ..."
  echo -e "clevis-pkcs11: pcscd running?:[$(ps auxf | grep [p]cscd)]\n"
  if ! ps auxf | grep [p]cscd;
  then
    echo "clevis-pkcs11: starting pcscd ..."
    pcscd --disable-polkit
  fi
fi
pkcs11-tool -L
