---
name: "Basic compilation and tests"
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: build systemd applications
        run: make -C systemd
      - name: basic systemd applications test
        run: make -C systemd test
